### ISSUE TITLE
Can not resolve module

### ISSUE THREAD

**Issue by Clonescody** [react-native-community/react-native-svg#1165]
Hey guys, I recently ejected my app and updated to ExpoKit 35, and since then, I can't launch the app on iOS anymore because there's a problem with the react-native-svg module.

Commands : 
- `expo install react-native-svg`
- `cd ios && pod install`
- `cd .. && expo start -c`
- `Build and run` on Xcode

Error below : 

> While trying to resolve module `react-native-svg` from file `/project/assets/illustrations/demo.svg`, the package `/project/node_modules/react-native-svg/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/project/node_modules/react-native-svg/src/index.ts`. Indeed, none of these files exist:

> `/project/node_modules/react-native-svg/src/index.ts(.native||.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.svg|.native.svg|.svg|.ios.json|.native.json|.json)`

> `/project/node_modules/react-native-svg/src/index.ts/index(.native||.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.svg|.native.svg|.svg|.ios.json|.native.json|.json)`

Any of you guys had this issue before ? Any help appreciated :) 

I am currently using the following versions : 

Expo : 35.0.0
ExpoKit  : 35.0.1
React-native : https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz ( SDK 35 )
React-native-svg : 9.12.0 ( When installing, yarn says that version ~9.9.2 is required, but it gaves me the same error anyways )
CocoaPods : 1.8.3
Xcode : 11.1

**Comment by msand** [comment]
Hmm, well that file certainly exists in the repo and on npm, can you check that it exists in your node_modules?

**Comment by feliperoan** [comment]
Hi I have the same error for a few hours
I already deleted modules reinstall from scratch and I don't have the solution
`Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `css-select` from `D:\Developement\dos\CloudMobile\SiigoApp\node_modules\react-native-svg\src\css.tsx`: Module `css-select` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.`

this from today, do you know how I can fix it?

**Comment by msand** [comment]
@feliperoan Can you try v9.13.2? Or `yarn add css-tree css-select` https://github.com/react-native-community/react-native-svg/issues/1166#issuecomment-545573905

**Comment by feliperoan** [comment]
> @feliperoan Can you try v9.13.2? Or `yarn add css-tree css-select` [#1166 (comment)](https://github.com/react-native-community/react-native-svg/issues/1166#issuecomment-545573905)

perfect, thank you

**Comment by Clonescody** [comment]
@msand The package.json exists inside the react-native-svg module, however, as specified in the error, the `/node_modules/react-native-svg/src/index.ts` file is missing , `index.js` is present thought

**Comment by msand** [comment]
@Clonescody seems you have some strange combination of old code and new code, index.js hasn't existed for quite some time. https://unpkg.com/browse/react-native-svg@9.13.2/src/

**Comment by Clonescody** [comment]
@msand, I updated to 9.13.2, still getting the same error, even thought the `.ts` file is present this time :

ls -l ./node_modules/react-native-svg/src/

-rw-r--r--    ReactNativeSVG.ts
-rw-r--r--    ReactNativeSVG.web.ts
-rw-r--r--    css.tsx
drwxr-xr-x   elements
-rw-r--r--    index.d.ts
-rw-r--r--    index.js.flow
-rw-r--r--    index.ts
drwxr-xr-x   lib
-rw-r--r--    xml.tsx

I tried to remove/reinstall node_modules completely but still nothing :(

**Comment by msand** [comment]
Can you try this?

```
watchman watch-del-all
rm -fr $TMPDIR/react-*
react-native start --reset-cache
```

**Comment by Clonescody** [comment]
I tried the commands, when i'm starting the packager with `react-native start --reset-cache` and launching the app with `react-native run-ios`, the app is loading but ends up crashing after a black screen. 

When using `expo start -c` instead of the `react-native start` command, I keep getting the module error

**Comment by msand** [comment]
Can you try making a clean project and try it there?

**Comment by Clonescody** [comment]
I did already : 
`expo init test`
`yarn add react-native-svg@9.13.2`
`expo eject` => ExpoKit
`cd ios && pod install`
`expo start -c`
`Build and Run` on Xcode 

And everything works fine :/

**Comment by RobertMeGusta** [comment]
I had the same issue, with same steps and same outcome. Figured out that in my app.json i had 
`"packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": ["js","jsx","svg",]
    },`
insead of 
`"packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": [ "js","jsx","svg","ts","tsx"]
    },`
changing that fixed my issue

**Comment by Clonescody** [comment]
I tried everything that was suggested but it still didn't worked. 

I fixed the issue by going back to my pre-detached app state and redoing the whole installation.

Thanks anyways for the help.

**Comment by walidvb** [comment]
Had the same issue, adding `ts` and `tsx` to the list of `sourceExts` as per https://github.com/react-native-community/react-native-svg/issues/1165#issuecomment-546101731 fixed it

**Comment by ExcellentSP** [comment]
@walidvb, Can confirm. [#1165 (comment)](https://github.com/react-native-community/react-native-svg/issues/1165#issuecomment-546101731) fixed my issue as well.

**Comment by ensargunesdogdu** [comment]
I could not manage to resolve issue by @RobertMeGusta comments. Still having the same problem :(

**Comment by Asleepace** [comment]
[This thread](https://stackoverflow.com/questions/59300743/react-native-debug-mode-throws-an-error-why-is-that-so) on SO helped me out:

Delete `Pods` and `Podfile.lock` then run `pod install`

**Comment by 07734** [comment]
To reconfirm this can be resolved, when using `metro.config.js` by adding "ts" and "tsx" to the `sourceExts` as follows:

```
module.exports = {
  resolver: {
    sourceExts: ["js", "ts", "jsx", "tsx", "json"],
  },
  ...
```

**Comment by rickli1989** [comment]
#1165 (comment) fixed my issue as well.

**Comment by huzaima** [comment]
I'm still facing this issue with react-native-svg latest version.

ERROR: error: bundling failed: Error: Unable to resolve module `css-tree` from `node_modules/react-native-svg/src/css.tsx`: css-tree could not be found within the project or in these directories:
  ../../node_modules

OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 129.73 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

**Comment by whatdtech** [comment]
> > @feliperoan Can you try v9.13.2? Or `yarn add css-tree css-select` [#1166 (comment)](https://github.com/react-native-community/react-native-svg/issues/1166#issuecomment-545573905)
> 
> perfect, thank you

I think problem is with react-native-svg >= 12.0.0. Yarn add react-native-svg@11.0.0 solved all issues

**Comment by youssame** [comment]
> > > @feliperoan Can you try v9.13.2? Or `yarn add css-tree css-select` [#1166 (comment)](https://github.com/react-native-community/react-native-svg/issues/1166#issuecomment-545573905)
> > 
> > 
> > perfect, thank you
> 
> I think problem is with react-native-svg >= 12.0.0. Yarn add react-native-svg@11.0.0 solved all issues

you're an angel

**Comment by neilakoh** [comment]
@Asleepace this worked . . removing the Podfile.lock is necessary to get the updates from lastest css-tree modules you installed. In my case the error was "Unable to resolve module `./HexColor`" it turns out they rename it from HexColor to Hash so in order to get the updates "Podfile.lock" file has to be removed before running pod install.

**Comment by atulugale11** [comment]
`npm i react-native-svg` solved for me

**Comment by Rajan-Savaliya-spt** [comment]
npm i react-native-svg work for me to

**Comment by ummartoor** [comment]
> npm i react-native-svg

what about yarn that didn't work ? i'm trying with that

**Comment by aqibhassanzeb** [comment]
yarn add react-native-svg @ummartoor

**Comment by AsadAsh006** [comment]
I am facing that issue I already imported the css according to error but still facing same error " Error: [react-native-svg] You are trying to import a component `WithLocalSvg` that has been moved to a sub-package. Change your import from `react-native-svg` to `react-native-svg/css`."

**Comment by emeraldknight-sp** [comment]
`yarn add react-native-svg` solved here

**Comment by eucliwoodhell** [comment]
`import { Path, Svg } from 'react-native-svg/src/elements'` solved here
