### ISSUE TITLE
Android: Press events not firing on large SVGs (snack available)

### ISSUE THREAD

**Issue by AdamGerthel** [react-native-community/react-native-svg#1221]
# Bug

Press events are not fired on Android devices if the SVG element pressed is further away than the device's window (even if visible when rendered).

## Environment info

Library version: 9.13.6

## Steps To Reproduce

1. Create an SVG that is larger than the device's window size and place a circle outside the device's window size (but inside the SVG). Add a press event to the circle.
2. Launch it on Android
3. Test to see if the circle react to onPress. 

See snack further down.

**Describe what you expected to happen:**
I would expect all components to behave the same since they are identical, i.e. I would expect the press events to work no matter what coordinates are used.

## Reproducible sample code

https://snack.expo.io/@insats/android-svg-bug (number 8 does not react to press events)

**Comment by theasc** [comment]
The same problem happens to me, off view element event does not fire at all.

**Comment by msand** [comment]
I suspect that the transforms are accounted for correctly in the clipping / bounds calculations, anyone interested in taking a look at it? I can probably point out some relevant code regions and answer any questions

**Comment by AdamGerthel** [comment]
@msand It seems like this isn't a bug with react-native-svg after all. I've managed to reproduce it with plain react native: https://snack.expo.io/@insats/android-touch-event-bug

I've posted there: https://github.com/facebook/react-native/issues/27647

**Comment by msand** [comment]
Ah, good to know. Anyway, it seems quite probable to me that it would relate to transforms and the bounds clipping calculations. Android prefers (almost requires) that the clipping mode can only constrain the bounds, such that it can decide if a view can possibly contain the touch event by only considering it's bounds, rather than having to traverse the entire tree with depth-first-search, reversed / sorted such that it accounts for z-index / document / render tree order and overlap of visibility.

It might be that you need to have a specific combination of (Animated.createAnimatedComponent wrapped) View, ScrollView, Svg, and G elements, with specific styles / transforms, to get it to work as expected in android. Other cases, and especially ones that developers likely expect to work, would be great to get cross-platform support for.

**Comment by msand** [comment]
One workaround is to ensure that all parent elements are big enough, either set a background color, a border, or make overflow hidden to see that the bounds of the ancestors clip the views that you want to respond to interactions.

```jsx
import * as React from 'react';
import {
  Text,
  View,
  StyleSheet,
  PanResponder,
  Animated,
  TouchableOpacity,
} from 'react-native';
import Constants from 'expo-constants';
import points from './assets/points';

const maxX = points.reduce((acc, p) => Math.max(acc, p.x), 0) + 25;
const maxY = points.reduce((acc, p) => Math.max(acc, p.y), 0) + 25;

export default class App extends React.Component {
  constructor(props, context) {
    super(props, context);
    let val = { x: 0, y: 0 };
    let xy = new Animated.ValueXY();
    xy.addListener(value => (val = value));
    this.pan = PanResponder.create({
      onMoveShouldSetResponderCapture: () => true,
      onMoveShouldSetPanResponderCapture: () => true,
      onPanResponderGrant: (e, gestureState) => {
        xy.setOffset({ x: val.x, y: val.y });
        xy.setValue({ x: 0, y: 0 });
      },
      onPanResponderMove: Animated.event([
        null,
        { dx: xy.x, dy: xy.y, useNativeDriver: true },
      ]),
      onPanResponderRelease: () => {
        xy.flattenOffset();
      },
    });
    this.xy = xy;
  }
  render() {
    return (
      <View style={styles.container} {...this.pan.panHandlers}>
        <Animated.View
          style={[
            styles.map,
            {
              width: maxX,
              height: maxY,
              transform: this.xy.getTranslateTransform(),
            },
          ]}>
          {points.map((p, i) => (
            <Point key={i} i={i} p={p} />
          ))}
        </Animated.View>
      </View>
    );
  }
}

class Point extends React.PureComponent {
  onPress = () => alert('Pressed ' + this.props.i);
  render() {
    const {
      i,
      p: { x, y },
    } = this.props;
    return (
      <View
        style={[
          {
            top: y,
            left: x,
            position: 'absolute',
          },
        ]}>
        <TouchableOpacity style={styles.button} onPress={this.onPress}>
          <Text style={styles.buttonText}>{i}</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#cccccc',
    flex: 1,
  },
  map: {
    backgroundColor: 'white',
  },
  button: {},
  buttonText: {
    width: 25,
    height: 25,
    lineHeight: 25,
    color: 'white',
    textAlign: 'center',
    backgroundColor: 'blue',
  },
});


```

**Comment by msand** [comment]
Actually, I realized I've fixed this issue before in react-native-svg, e.g. this seems to work correctly:
https://snack.expo.io/@msand/android-touch-event-bug
```jsx
import * as React from 'react';
import {
  View,
  StyleSheet,
  PanResponder,
  Animated,
  TouchableOpacity,
} from 'react-native';
import { Svg, G, Rect, Text } from 'react-native-svg';
import Constants from 'expo-constants';
import points from './assets/points';

const AnimatedG = Animated.createAnimatedComponent(G);

const maxX = points.reduce((acc, p) => Math.max(acc, p.x), 0) + 25;
const maxY = points.reduce((acc, p) => Math.max(acc, p.y), 0) + 25;

export default class App extends React.Component {
  constructor(props, context) {
    super(props, context);
    let val = { x: 0, y: 0 };
    let xy = new Animated.ValueXY();
    xy.addListener(value => (val = value));
    this.pan = PanResponder.create({
      onMoveShouldSetResponderCapture: () => true,
      onMoveShouldSetPanResponderCapture: () => true,
      onPanResponderGrant: (e, gestureState) => {
        xy.setOffset({ x: val.x, y: val.y });
        xy.setValue({ x: 0, y: 0 });
      },
      onPanResponderMove: Animated.event([
        null,
        { dx: xy.x, dy: xy.y, useNativeDriver: true },
      ]),
      onPanResponderRelease: () => {
        xy.flattenOffset();
      },
    });
    this.xy = xy;
  }
  render() {
    return (
      <View style={styles.container} {...this.pan.panHandlers}>
        <Svg width="100%" height="100%">
          <AnimatedG
            style={[
              {
                transform: this.xy.getTranslateTransform(),
              },
            ]}>
            <Rect fill="white" width={400} height={600} />
            {points.map((p, i) => (
              <Point key={i} i={i} p={p} />
            ))}
          </AnimatedG>
        </Svg>
      </View>
    );
  }
}

class Point extends React.PureComponent {
  onPress = () => alert('Pressed ' + this.props.i);
  render() {
    const {
      i,
      p: { x, y },
    } = this.props;
    return (
      <G transform={`translate(${x}, ${y})`}>
        <Rect
          fill="blue"
          width={25}
          height={25}
          onPress={this.onPress}
          onClick={this.onPress}
        />
        <Text x={12.5} y={17} textAnchor="middle" style={styles.buttonText}>
          {i}
        </Text>
      </G>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#cccccc',
    flex: 1,
  },
  buttonText: {
    fill: 'white',
    textAlign: 'center',
  },
});

```

**Comment by msand** [comment]
Another (less complete compared to previous one) workaround, which might be useful for debugging the issue in react-native; is using ScrollView and comparing how it behaves differently from the example you made:

```jsx
import * as React from 'react';
import {Text, ScrollView, StyleSheet, TouchableOpacity} from 'react-native';
import points from './points';

const side = 1000;

export default class App extends React.Component {
  render() {
    return (
      <ScrollView contentContainerStyle={{height: side}}>
        <ScrollView horizontal contentContainerStyle={{width: side}}>
          {points.map(({x, y}, i) => (
            <TouchableOpacity
              key={i}
              style={[
                styles.button,
                {
                  left: x,
                  top: y,
                },
              ]}
              onPress={() => alert(i)}>
              <Text style={styles.text}>{i}</Text>
            </TouchableOpacity>
          ))}
        </ScrollView>
      </ScrollView>
    );
  }
}

const r = 25;

const styles = StyleSheet.create({
  text: {
    color: 'white',
    textAlign: 'center',
  },
  button: {
    width: r,
    height: r,
    borderRadius: r,
    position: 'absolute',
    backgroundColor: 'blue',
  },
});

```

**Comment by msand** [comment]
Another workaround:

```jsx
import * as React from 'react';
import {
  Text,
  View,
  Animated,
  Dimensions,
  StyleSheet,
  PanResponder,
  TouchableOpacity,
} from 'react-native';
import points from './points';

const initial = {x: 0, y: 0};
const {width, height} = Dimensions.get('window');
const maxX = points.reduce((acc, p) => Math.max(acc, p.x), 0) + 25;
const maxY = points.reduce((acc, p) => Math.max(acc, p.y), 0) + 25;

export default class App extends React.Component {
  constructor(props, context) {
    super(props, context);
    const xy = new Animated.ValueXY();
    const {x: dx, y: dy} = xy;
    let offset = initial;
    xy.addListener(flatOffset => {
      offset = flatOffset;
    });
    const {panHandlers} = PanResponder.create({
      onMoveShouldSetPanResponderCapture: () => true,
      onPanResponderGrant: () => {
        xy.setOffset(offset);
        xy.setValue(initial);
      },
      onPanResponderMove: Animated.event([null, {dx, dy}]),
      onPanResponderRelease: () => {
        xy.flattenOffset();
      },
    });
    this.translateXY = {
      transform: xy.getTranslateTransform(),
    };
    this.panXY = panHandlers;
  }
  render() {
    const {panXY, translateXY} = this;
    return (
      <View style={styles.container} {...panXY}>
        <Animated.View
          style={[
            translateXY,
            {
              width: maxX,
              height: maxY,
            },
          ]}>
          <View style={styles.map} />
          {points.map(({x, y}, i) => (
            <TouchableOpacity
              key={i}
              style={[
                styles.button,
                {
                  left: x,
                  top: y,
                },
              ]}
              onPress={() => alert(i)}>
              <Text style={styles.text}>{i}</Text>
            </TouchableOpacity>
          ))}
        </Animated.View>
      </View>
    );
  }
}

const r = 25;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#cccccc',
  },
  map: {
    width,
    height,
    borderWidth: 1,
    borderColor: 'black',
    position: 'absolute',
    backgroundColor: 'white',
  },
  text: {
    color: 'white',
    textAlign: 'center',
  },
  button: {
    width: r,
    height: r,
    borderRadius: r,
    position: 'absolute',
    backgroundColor: 'blue',
  },
});

```

This issue is certainly related to TouchTargetHelper.java in react-native, and also
public boolean pointInView(float localX, float localY, float slop)
 in Android.View, which is called from:
protected boolean isTransformedTouchPointInView(float x, float y, View child, PointF outLocalPoint)
in Android.ViewGroup

mostly due to

```java
    /**
     * Utility method to determine whether the given point, in local coordinates,
     * is inside the view, where the area of the view is expanded by the slop factor.
     * This method is called while processing touch-move events to determine if the event
     * is still within the view.
     *
     * @hide
     */
    public boolean pointInView(float localX, float localY, float slop) {
        return localX >= -slop && localY >= -slop && localX < ((mRight - mLeft) + slop) &&
                localY < ((mBottom - mTop) + slop);
    }
```

Not allowing touch events onto children which are outside the clip bounds. Which is an issue when you're using absolutely positioned elements, as they don't contribute to the width and height of the parent.

**Comment by msand** [comment]
So, either use the proper svg solution, or find a way to fix the issue in react-native. Seems like the issue is actually that absolutely positioned children don't contribute to the bounds used in the logic for finding if the point is inside the view. Alternatively, change the logic in TouchTargetHelper to ignore the bounds, and do a complete DFS of the entire tree, without the short-circuit of bounds intersection on non-leaf views. Svg has all elements absolutely positioned, so it's quite natural it's been fixed here already.

**Comment by AdamGerthel** [comment]
@msand Thanks, your explanations are quite helpful - although the deeply nested logic of how Android works in the native layer is way over my head.

[The solution to use an animated group](https://github.com/react-native-community/react-native-svg/issues/1221#issuecomment-570059335) worked perfectly (albeit your snack doesn't work on my Android device, nothing happens when any blue dot is pressed). In either case, it solved the problem for me, and all touch events work as expected on both iOS and Android. 

But it actually caused a new problem: The initial  XY position is not respected. Try changing the values of the `initial` variable in your snack and see - the default position (before any pan etc. is performed) should change, but it doesn't. The rendered element defaults to 0 0. Subsequent renders seem to work, but not the initial one.

**Comment by AdamGerthel** [comment]
Ahh, I finally got it working (for my specific component – which is an in-game map in an RPG), by simply moving the transform to the SVG root element instead, (i.e. `const AnimatedSvg = Animated.createAnimatedComponent(Svg.Svg)`). Thank god (or @msand) 🙏

**Comment by msand** [comment]
If you want to add an additional static transform, then I'd recommend wrapping the AnimatedG with another G and set the transform attribute like this:

```jsx
  render() {
    const {
      panXY,
      translateXY,
      props: { points = defaultPoints, x = 100, y = 0 },
    } = this;
    return (
      <View style={styles.container} {...panXY}>
        <Svg width="100%" height="100%" fill="white">
          <G transform={`translate(${x},${y})`}>
            <AnimatedG style={translateXY}>
              <Rect width="100%" height="100%" />
              <Points points={points} />
            </AnimatedG>
          </G>
        </Svg>
      </View>
    );
  }
```

or directly on the Svg element:

```jsx
  render() {
    const {
      panXY,
      translateXY,
      props: { points = defaultPoints, x = 100, y = 0 },
    } = this;
    return (
      <View style={styles.container} {...panXY}>
        <Svg
          fill="white"
          width="100%"
          height="100%"
          transform={`translate(${x},${y})`}>
          <AnimatedG style={translateXY}>
            <Rect width="100%" height="100%" />
            <Points points={points} />
          </AnimatedG>
        </Svg>
      </View>
    );
  }
}
```

The `initial` variable is only used to reset the Animated.ValueXY, and shouldn't be changed.

**Comment by AdamGerthel** [comment]
I would've expected that the rendered, initial, animated group would respect the initial transform values, but they don't. If you look at this snack (yours, with a tiny edit):
https://snack.expo.io/@insats/android-touch-event-bug---group

I've changed `const xy = new Animated.ValueXY();` to `const xy = new Animated.ValueXY({ x: 50, y: 50 });`, but the initial render still shows the group at 0 0. Isn't that a bug, albeit a totally different one? If I use console.log to check the values at render, they are indeed 50 50, but the

**Comment by msand** [comment]
Try doing this instead:

```jsx
const initial = { x: 0, y: 0 };
const initialOffset = { x: 50, y: 50 }; 

export default class PointsPanSurface extends React.PureComponent {
  constructor(props, context) {
    super(props, context);
    const xy = new Animated.ValueXY();
    const { x: dx, y: dy } = xy;
    let offset = initial;
    xy.addListener(flatOffset => {
      offset = flatOffset;
    });
    xy.setValue(initialOffset);
    xy.flattenOffset();
```

Or alternatively:

```jsx
const initial = { x: 0, y: 0 };
const initialOffset = { x: 50, y: 50 }; 

export default class PointsPanSurface extends React.PureComponent {
  constructor(props, context) {
    super(props, context);
    const xy = new Animated.ValueXY(initialOffset);
    const { x: dx, y: dy } = xy;
    let offset = initialOffset;
    xy.addListener(flatOffset => {
      offset = flatOffset;
    });
```

**Comment by msand** [comment]
Changed initial to initialGestureDelta, this is probably a more descriptive name:

```jsx
const AnimatedG = Animated.createAnimatedComponent(G);

const initialGestureDelta = { x: 0, y: 0 };
const initialOffset = { x: 50, y: 50 }; 

export default class PointsPanSurface extends React.PureComponent {
  constructor(props, context) {
    super(props, context);
    const xy = new Animated.ValueXY(initialOffset);
    const { x: dx, y: dy } = xy;
    let offset = initialOffset;
    xy.addListener(flatOffset => {
      offset = flatOffset;
    });
    const { panHandlers } = PanResponder.create({
      onMoveShouldSetResponderCapture: () => true,
      onMoveShouldSetPanResponderCapture: () => true,
      onPanResponderGrant: () => {
        xy.setOffset(offset);
        xy.setValue(initialGestureDelta);
      },
      onPanResponderMove: Animated.event([null, { dx, dy }]),
      onPanResponderRelease: () => {
        xy.flattenOffset();
      },
    });
    this.translateXY = {
      transform: xy.getTranslateTransform(),
    };
    this.panXY = panHandlers;
  }
  render() {
    const {
      panXY,
      translateXY,
      props: { points = defaultPoints },
    } = this;
    return (
      <View style={styles.container} {...panXY}>
        <Svg width="100%" height="100%" fill="white">
          <AnimatedG style={translateXY}>
            <Rect width="100%" height="100%" />
            <Points points={points} />
          </AnimatedG>
        </Svg>
      </View>
    );
  }
}
```

**Comment by msand** [comment]
I guess this can be closed by now. Reply if still having issues.

**Comment by subashcs** [comment]
> I guess this can be closed by now. Reply if still having issues.

What should i do, it runs with expo on web browser but not on android device 
`import React, { Component, useState } from "react";
import { PanResponder, Animated, View, StyleSheet } from "react-native";

import Svg, {
  Circle,
  Ellipse,
  G,
  Text,
  TSpan,
  TextPath,
  Path,
  Polygon,
  Polyline,
  Line,
  Rect,
  Use,
  Image,
  Symbol,
  Defs,
  LinearGradient,
  RadialGradient,
  Stop,
  ClipPath,
  Pattern,
  Mask,
} from "react-native-svg";

import { Audio } from "expo-av";
import tigerAudio from "../assets/tiger.mp3";
import { mv } from "../constants";
import populateCoordinates, { getMoveAngle } from "../utils";

export interface NodeProps {
  n: number;
  spacing: number;
  vSpacing: number;
  selectTigerToMove: (position: number) => void | undefined;
  selected: boolean;
  movable: boolean;
  moveTiger: (
    initialPosition: number,
    newPosition: number,
    step: number
  ) => void;
  isMoveAllowed: (
    initialPosition: number,
    newPosition: number,
    move: string,
    step: number
  ) => boolean;
  resetMove: (initialPosition: number) => void;
}
  const AnimatedUse = Animated.createAnimatedComponent(Use);

const scroll = false;

const zeroDelta = { x: 0, y: 0 };

const Tiger: React.FC<NodeProps> = (props: NodeProps) => {
  let { n, spacing, vSpacing, movable, selected } = props;
  let initialX = spacing / 2;
  let initialY = vSpacing / 2.5;
  let colPosition = n % 5;
  let rowPosition = Math.floor(n / 5);
  let cx = colPosition * spacing + initialX;
  let cy = initialY + rowPosition * vSpacing;

  // console.log("got", colPosition, rowPosition);

  const xy = new Animated.ValueXY();
  const { x: dx, y: dy } = xy;
  let offset = zeroDelta;
  xy.addListener((flatOffset) => {
    console.log("got flatOffset", flatOffset);
    offset = flatOffset;
  });

  const findNextPosition = (
    currentPosition: number,
    move: string | undefined,
    step: number
  ) => {
    if (!move) {
      console.log("move not defined , position cant be found");
      return currentPosition;
    }
    let currentPosOffset = 0;
    switch (move) {
      case mv.top: {
        currentPosOffset = -5;
        break;
      }
      case mv.topRight: {
        currentPosOffset = -4;
        break;
      }
      case mv.right: {
        currentPosOffset = 1;
        break;
      }
      case mv.bottomRight: {
        currentPosOffset = 6;
        break;
      }
      case mv.bottom: {
        currentPosOffset = 5;
        break;
      }
      case mv.bottomLeft: {
        currentPosOffset = 4;
        break;
      }
      case mv.left: {
        currentPosOffset = -1;
        break;
      }
      case mv.topLeft: {
        currentPosOffset = -6;
        break;
      }
      default: {
        currentPosOffset = 0;
        break;
      }
    }
    currentPosOffset = step === 2 ? currentPosOffset * 2 : currentPosOffset;
    return currentPosition + currentPosOffset;
  };

  const { panHandlers } = PanResponder.create({
    onStartShouldSetPanResponder: (evt, gestureState) => movable,
    onMoveShouldSetPanResponderCapture: () => movable,
    onPanResponderGrant: () => {
      let finalizedOffset = offset;
      xy.setOffset(finalizedOffset);
      // xy.setOffset({ x: 0, y: 0 });

      xy.setValue(zeroDelta);
    },
    onPanResponderMove: (_, gesture) => {
      let ang = getMoveAngle(gesture.dx, gesture.dy);
      console.log("got", ang);
      let newCoords = populateCoordinates(ang, gesture.dx, gesture.dy);
      console.log("newcoords", newCoords);
      xy.x.setValue(newCoords.x);
      xy.y.setValue(newCoords.y);
    },
    onPanResponderRelease: (e, gestureState) => {
      xy.flattenOffset();
      let initialPosition = n;
      let angle = getMoveAngle(gestureState.dx, gestureState.dy);
      console.log("got angle", angle);
      let { direction } = populateCoordinates(
        angle,
        gestureState.dx,
        gestureState.dy
      );
      let step =
        gestureState.dx >= 1.5 * spacing ||
        gestureState.dx <= -1.5 * spacing ||
        gestureState.dy >= 1.5 * vSpacing ||
        gestureState.dy <= -1.5 * vSpacing
          ? 2
          : 1;
      console.log("got step", step);
      //how to reject pan if gestureState value is more than 120

      let nextPosition = findNextPosition(initialPosition, direction, step);
      //while finding nex position check validity
      console.log(
        "got direction to ",
        nextPosition,
        " from ",
        initialPosition,
        direction
      );
      let moveAllowed = props.isMoveAllowed(
        initialPosition,
        nextPosition,
        direction,
        step
      );
      if (moveAllowed) {
        props.moveTiger(initialPosition, nextPosition, step);
      } else {
        console.log("resetting move");
        props.resetMove(initialPosition);
      }

      // console.log("pan resopnder released", gestureState.dx, gestureState.dy);
    },
  });

  const panXY = {
    style: {
      transform: xy.getTranslateTransform(),
      position: "absolute",
    },
    onClick: async () => {
      // try {
      //   const {
      //     sound: soundObject,
      //     status,
      //   } = await Audio.Sound.createAsync(tigerAudio, { shouldPlay: true });
      //   // Your sound is playing!
      // } catch (error) {
      //   // An error occurred!
      // }
    },
    ...panHandlers,
  };

  return (
    <>
      <Symbol id="tiger" viewBox="0 0 60 60">
        <G fill="none" >
          <Path
            d="M41.94 49.77A6.7 6.7 0 0039 40h-.09a1.56 1.56 0 00.09-.7v-.81a1.34 1.34 0 00-.89-1.35A34.17 34.17 0 0030 36a64.2 64.2 0 00-8.06 1.2 1.32 1.32 0 00-.94 1.37v.73a1.56 1.56 0 00.14.66h-.09A6.64 6.64 0 0017 46.15a6.72 6.72 0 001.05 3.61C15.39 47.05 6.16 38.79 7.54 28a24.4 24.4 0 013.78-8.86A23.32 23.32 0 0120.83 11a22 22 0 0118.34 0 23.42 23.42 0 019.51 8.1 24.4 24.4 0 012.64 5 .14.14 0 000 .06c4.68 12.75-6.42 22.6-9.38 25.61z"
            fill="#ff9801"
          />
          <Path
            d="M51.34 24.2a.14.14 0 010-.06 24.4 24.4 0 00-2.64-5A23.42 23.42 0 0039.17 11 21.9 21.9 0 0030 9c-.5 0-1 .02-1.5.06A21.79 21.79 0 0136.17 11a23.42 23.42 0 019.51 8.1 24.4 24.4 0 012.64 5 .14.14 0 000 .06C51.66 33.25 47 40.84 43 45.56v.59a6.65 6.65 0 01-1.06 3.62C44.9 46.76 56 36.91 51.34 24.2z"
            fill="#f57c00"
          />
          <Path d="M19.27 55.85h-.08z" fill="#ff9801" />
          <Path
            d="M39 38.49c0 1 0 1.13-.14 1.47-.21.54.13.2-8.36 5.43a1 1 0 01-1 0C21 40.15 21.36 40.5 21.14 40a3 3 0 01-.14-1.43 1.32 1.32 0 01.94-1.37A64.2 64.2 0 0130 36a34.17 34.17 0 018.11 1.14c.565.2.929.752.89 1.35z"
            fill="#37474f"
          />
          <Path
            d="M41.94 49.77a6 6 0 00-.94 1.16 6.49 6.49 0 01-11-4.78c0-.65-.06-.37 0-.62a.94.94 0 00.51-.14C39 40.15 38.64 40.5 38.86 40a6.68 6.68 0 013.08 9.77z"
            fill="#f57c00"
          />
          <Path
            d="M40.69 55.88a19.93 19.93 0 01-21.38 0 5.77 5.77 0 00-.33-5 6.4 6.4 0 004.51 1.86A6.58 6.58 0 0030 46.15a6.58 6.58 0 006.5 6.64 6.4 6.4 0 004.5-1.86 5.7 5.7 0 00-.31 4.95z"
            fill="#ff9801"
          />
          <Path
            d="M41 50.93a6.46 6.46 0 01-3.67 1.8 6 6 0 00.35 3.15 20.42 20.42 0 01-9.19 3c.5.04 1 .06 1.5.06a20.26 20.26 0 0010.69-3.11 5.7 5.7 0 01.32-4.9zM30 46.15a6.49 6.49 0 01-11 4.78 5.55 5.55 0 00-.94-1.17A6.69 6.69 0 0121.14 40a1.2 1.2 0 00.48.58c8.55 5.26 8 5 8.37 5-.05.18.01.01.01.57z"
            fill="#f57c00"
          />
          <Path
            d="M22.81 27.14A4 4 0 0119 30a4.07 4.07 0 01-4-4.14 2.47 2.47 0 01.05-.61zM45 25.86A4.07 4.07 0 0141 30a4 4 0 01-3.82-2.86L45 25.25c.02.203.02.407 0 .61z"
            fill="#00bcd4"
          />
          <Path
            d="M55.08 18.74c-.19.31-.4.63-.61 1s-.43.65-.66 1l-2.35 3.41-.13.05a24.4 24.4 0 00-2.64-5 17.52 17.52 0 001.23-1.27C55 12 54.24 7.69 53.09 4.86c-.67-1.65-2.57-1.71-4.07-.75l-8.71 6.09 12.16-8.6a3.88 3.88 0 015.65 1.79c1.43 3.47 1.56 7.97-3.04 15.35z"
            fill="#37474f"
          />
          <Path
            d="M49.91 17.83a17.52 17.52 0 01-1.23 1.27 23.42 23.42 0 00-9.51-8.1l.82-.57h.07l.25-.18L49 4.11c1.5-1 3.4-.9 4.07.75C54.24 7.69 55 12 49.91 17.83z"
            fill="#f57c00"
          />
          <Path d="M48.68 19.1l-.01.01" fill="#ff9801" />
          <Path
            d="M11.32 19.1a24.4 24.4 0 00-2.64 5l-.13-.05-2.35-3.37c-.23-.34-.45-.66-.66-1s-.42-.65-.61-1C.32 11.36.45 6.86 1.88 3.39A3.88 3.88 0 017.53 1.6l13 9.18L11 4.11c-1.5-1-3.4-.9-4.07.75C5.76 7.69 5 12 10.09 17.83c.388.444.799.868 1.23 1.27z"
            fill="#37474f"
          />
          <Path
            d="M58.44 40.73a1 1 0 01-1.7.55.84.84 0 00-1.46.58A21.2 21.2 0 0150 55.68a1 1 0 01-1.32.11L46 53.8a1 1 0 00-1-.12 42.68 42.68 0 00-4.29 2.18 5.7 5.7 0 01.32-5 6.48 6.48 0 00.93-1.16c3-3 14.07-12.86 9.4-25.57a.14.14 0 010-.06c.18-.07-.1.3 2.48-3.46.31-.46.48-.7 1.28-1.94 3.29 5.33 4.78 13.55 3.32 22.06z"
            fill="#f5f5f5"
          />
          <Path
            d="M55.08 18.74c-.8 1.24-1 1.48-1.28 1.94l-.38.56c2.36 5.18 3.27 12.23 2 19.49a1 1 0 01-1.7.55.84.84 0 00-1.46.58A21.33 21.33 0 0147.59 55l1.09.81a1 1 0 001.32-.13 21.2 21.2 0 005.28-13.82.84.84 0 011.46-.58 1 1 0 001.7-.55c1.46-8.51-.03-16.73-3.36-21.99z"
            fill="#cfd8dc"
          />
          <Path d="M41 55.7h-.08" fill="#ff9801" />
          <Path
            d="M19.32 55.88c-.25-.25-3.44-1.79-4.33-2.2a1 1 0 00-1 .12l-2.66 2a1 1 0 01-1.33-.12 21.2 21.2 0 01-5.28-13.82.84.84 0 00-1.46-.58 1 1 0 01-1.7-.55c-1.46-8.51 0-16.73 3.36-22 .19.3.44.7 1.28 1.94 2.57 3.74 2.3 3.39 2.48 3.46A24.89 24.89 0 007.54 28c-1.38 10.79 7.85 19 10.51 21.76.268.427.587.82.95 1.17a5.77 5.77 0 01.32 4.95z"
            fill="#f5f5f5"
          />
          <Path
            d="M19 50.93a6.27 6.27 0 01-.94-1.17C15.39 47.05 6.16 38.79 7.54 28a24.89 24.89 0 011.14-3.86c-.18-.07.09.28-2.48-3.46-.84-1.24-1.09-1.68-1.28-1.94a21.1 21.1 0 00-1.34 2.5c2.16 3.14 1.93 2.83 2.1 2.9A24.89 24.89 0 004.54 28c-1.38 10.79 7.85 19 10.51 21.76.268.427.587.82.95 1.17a5.3 5.3 0 01.68 3.56 25.51 25.51 0 012.64 1.39 5.77 5.77 0 00-.32-4.95z"
            fill="#cfd8dc"
          />
          <Path d="M19.19 55.81h.08" fill="#ff9801" />
          <Path
            d="M20.83 11a23.32 23.32 0 00-9.51 8.09 17.52 17.52 0 01-1.23-1.27C5 12 5.76 7.69 6.91 4.86c.67-1.65 2.57-1.71 4.09-.75l9.54 6.67z"
            fill="#f57c00"
          />
          <Path d="M11.33 19.11l-.01-.01" fill="#ff9801" />
          <Path
            d="M59.05 3A4.88 4.88 0 0051.9.78L39.06 9.86A22.64 22.64 0 0021 9.9L8.06.75A4.88 4.88 0 001 3c-1.91 4.54-1 9.47 2.76 15.75C.36 24.48-.83 32.7.58 40.9a2 2 0 003.15 1.3 22 22 0 005.52 14.14 2 2 0 001.47.66c.87 0 1-.3 3.85-2.41 2.5 1.14 4 2 4.29 2.18a20.84 20.84 0 0022.26 0c.38-.18 1.67-1 4.3-2.18 2.91 2.18 3 2.4 3.86 2.4a1.94 1.94 0 001.47-.66 22 22 0 005.52-14.13 2 2 0 003.15-1.3c1.41-8.2.22-16.42-3.18-22.15C60.05 12.47 60.91 7.54 59.05 3zm-1.85.76c2.62 6.36-1.82 12.85-5.64 18.39A26.41 26.41 0 0050 19.24C54.09 15 56.24 10 54 4.49a3.17 3.17 0 00-1.55-1.67l.55-.38a2.88 2.88 0 014.2 1.33zM18.88 49.19a5.68 5.68 0 012-8c.37.3 8 5 8.12 5a5.48 5.48 0 01-9.22 4 6.77 6.77 0 00-.9-1zM30 37a32.68 32.68 0 017.86 1.11c.1.1.152.239.14.38 0 .57.06 1.07-.15 1.2L30 44.54l-7.87-4.85c-.2-.12-.15-.58-.15-1.12a.49.49 0 01.14-.39A57.51 57.51 0 0130 37zm9.13 4.21a5.68 5.68 0 012 8 6.77 6.77 0 00-.89 1.09 5.48 5.48 0 01-9.22-4c.09-.11 7.72-4.77 8.11-5.09zm.86-1.8v-.92a2.33 2.33 0 00-1.63-2.32l-1.13-.27-2-7.25 1.38-.34A4.94 4.94 0 0041 31a5.07 5.07 0 005-5 1.17 1.17 0 00.93-.61 1 1 0 000-.87l-1-2a1 1 0 00-1.78.9l.43.87-9.81 2.39a2 2 0 00-1.42 2.5l1.74 6.25a24.31 24.31 0 00-10.09.19l1.7-6.42a2 2 0 00-1.44-2.5l-9.8-2.38.43-.87a1 1 0 10-1.78-.9l-1 2a1 1 0 00.65 1.45H14a5.06 5.06 0 005 5 4.94 4.94 0 004.38-2.66l1.39.34-2 7.34-1 .2A2.32 2.32 0 0020 38.57v.84a7.6 7.6 0 00-4 6.85 34.53 34.53 0 01-5-6.73 13.59 13.59 0 004 .47 1 1 0 000-2 10.05 10.05 0 01-5.22-1.13 18.28 18.28 0 01-1.21-4.65A12.47 12.47 0 0016.88 36a1 1 0 000-2 10.36 10.36 0 01-8.4-5.21 4.9 4.9 0 01.29-1.58A4.73 4.73 0 0012 29a1 1 0 000-2c-.74 0-1.82-1.15-2.49-2.11A22.27 22.27 0 0129 10.05V15l-4.62-1.92a1 1 0 10-.76 1.84L29 17.17v3.37L18.14 19a1.01 1.01 0 00-.28 2L29 22.56v1a1 1 0 002 0v-1L42.14 21a1.01 1.01 0 00-.28-2L31 20.58v-3.35l5.39-2.31a1 1 0 10-.78-1.84l-4.61 2V10a22 22 0 0119.51 14.87C49.84 25.84 48.75 27 48 27a1 1 0 000 2 4.62 4.62 0 003.15-1.74c.105.516.181 1.036.23 1.56A10.38 10.38 0 0143 34a1 1 0 000 2 12.52 12.52 0 008.35-3.77 18.93 18.93 0 01-1.18 4.67A10.15 10.15 0 0145 38a1 1 0 000 2 13.74 13.74 0 003.94-.46A33.47 33.47 0 0144 46.25a7.59 7.59 0 00-4-6.84zm-1.35-11.59l5.29-1.29a3 3 0 01-5.29 1.29zm-17.3 0a3 3 0 01-5.25-1.3zM7.83 5.24c.43-1 1.69-.88 2.58-.31l8.53 6a24.55 24.55 0 00-7.7 6.7C7.8 13.91 6 9.85 7.83 5.24zm41 12.31a24.25 24.25 0 00-7.7-6.69L49.56 5c.92-.59 2.18-.77 2.61.29 1.83 4.55.04 8.59-3.36 12.26zM2.8 3.77A2.89 2.89 0 017 2.41l.58.41A3.13 3.13 0 006 4.49C3.75 10 5.93 15 10.07 19.27a25.13 25.13 0 00-1.61 2.92C4.71 16.76.17 10.17 2.8 3.77zM13.38 53l-2.63 2a20.07 20.07 0 01-5-13.17 1.84 1.84 0 00-3.17-1.27C1.31 33.36 2.24 25.9 5 20.66c2.2 3.3 2.62 3.61 2.53 3.88a25.88 25.88 0 00-1 3.34c0 .31-.09 1.07-.09 1.17C5.83 39 13.39 46.54 16.7 49.83l.59.59c.257.386.548.747.87 1.08a4.31 4.31 0 01.52 2.89c-1.27-.69-2.54-1.28-3.29-1.62a2 2 0 00-2.01.23zm7.13 2.43a7.27 7.27 0 00.21-2.19 7.42 7.42 0 009.28-3.3 7.42 7.42 0 009.28 3.3 7.27 7.27 0 00.21 2.19 19.08 19.08 0 01-18.98 0zM55 20.66c2.74 5.24 3.67 12.7 2.46 20a1.84 1.84 0 00-3.2 1.23 20.11 20.11 0 01-5 13.15l-2.64-2a2 2 0 00-2-.24c-.74.34-2 .93-3.29 1.62a4.37 4.37 0 01.52-2.89 7.61 7.61 0 00.87-1.08l.6-.59c3.62-3.6 13.07-13 9.28-25-.18-.81-.6.35 2.4-4.2z"
            fill="#000"
          />
        </G>
      </Symbol>
      <AnimatedUse
        href="#tiger"
        x={cx - spacing / 4}
        y={cy - spacing / 4}
        fill={"yellow"}
        width={spacing / 2}
        height={spacing / 2}
        opacity={movable ? 1 : 0.8}
        {...panXY}
      />
      <Defs>
        <LinearGradient id="linear" x1="0%" y1="0%" x2="100%" y2="0%">
          <Stop offset="0%" stopColor="#05a" />
          <Stop offset="10%" stopColor="#0a5" />

          <Stop offset="30%" stopColor="transparent" />
          <Stop offset="60%" stopColor="transparent" />

          <Stop offset="80%" stopColor="#05a" />
          <Stop offset="100%" stopColor="#0a5" />
        </LinearGradient>
      </Defs>
      {selected && (
        <Rect
          fill="none"
          stroke="url(#linear)"
          strokeWidth={3}
          x={cx - spacing / 3.6}
          rx={10}
          y={cy - spacing / 3.6}
          width={spacing / 1.8}
          height={spacing / 1.8}
        />
      )}
    </>
  );
};
export default Tiger;
`

**Comment by robertcreaner** [comment]
Hi @msand I'm running into a similar issue described above, where the onPress function doesn't fire on polygons rendered inside of a wide svg canvas. (only on android). I'm not sure at which point it breaks, but it only seems to occur on wide svgs. 

I've attached a video of the issue below, where the viewport width is 7500 px:
https://github.com/software-mansion/react-native-svg/assets/12414548/702d9ac5-7d0d-49d7-983a-e5f4bb22df0b

As you can see, the polygons on the right side of the svg don't get highlighted when pressed. 

I've considered applying a transform to the polygons but it's a bit more difficult since they contain multiple points, not just an x,y coordinate. Any ideas how I can solve this? 🙏  I've been at this issue for months now and I'm at a complete loss 

SVG component:
`<GestureDetector gesture={gestures}>
                    <View
                        style={[
                            styles.container,
                            gestureHandlerContainerStyle,
                            {
                                width: containerDimensions.width,
                                height: containerDimensions.height,
                            },
                        ]}
                    >
                        <Animated.View
                            style={[
                                styles.content,
                                {
                                    width: contentDimensions.width,
                                    height: contentDimensions.height,
                                },
                                animatedStyle,
                            ]}
                        >
                            <Svg
                                height={svgCanvasSize.height}
                                width={svgCanvasSize.width}
                                viewBox={`0 0 ${vbWidth} ${vbHeight}`}
                                preserveAspectRatio="none"
                            >
                                <TouchablePolygons/>
                            </Svg>
                        </Animated.View>
                    </View>
                </GestureDetector>`

Touchable Polygon:
`...
return (
            <G>
                {holds.map((hold) => {
                    return (
                        <Polygon
                            key={hold.id}
                            points={hold.touchPolygonStr}
                            fillOpacity={0}
                            fill="black"
                            onPress={() => this.toggleHoldAction(hold)}
                        />
                    );
                })}
            </G>
        );
...`
